export  const navItems=[
    {
      id:Math.random(),
      path:'/',
      item:"Home"
    },{
      id:Math.random(),
      path:"/blog",
      item:"Blog"
    },{
      id:Math.random(),
      path:"/projects",
      item:"Projects"
    },{
      id:Math.random(),
      path:"/github",
      item:"Github"
    },{
      id:Math.random(),
      path:"#contact",
      item:"Contact"
    }
  ]